# Generated by Django 5.2.6 on 2025-09-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlerequest',
            old_name='content',
            new_name='text',
        ),
    ]
