# Generated by Django 5.2.6 on 2025-10-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_competition_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='project_file',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='team_members',
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
