# Generated by Django 5.2.6 on 2025-10-06 12:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_participant_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='engineer_photos/')),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_visibility', models.CharField(choices=[('full', 'Full Address'), ('area', 'Area Only (City/State)'), ('hidden', 'No Location Shown')], default='area', max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_freelancer', models.BooleanField(default=False)),
                ('availability', models.CharField(choices=[('available', 'Available for Projects'), ('limited', 'Limited Availability'), ('unavailable', 'Not Taking New Clients')], default='available', max_length=20)),
                ('professional_summary', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=200)),
                ('website_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.country')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('bs', 'Bachelor of Science'), ('ms', 'Master of Science'), ('phd', 'PhD'), ('associate', 'Associate Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=50)),
                ('field_of_study', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2030)])),
                ('achievements', models.TextField(blank=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='articles.engineer')),
            ],
            options={
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='articles.engineer')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('branch', 'Branch Office'), ('regional', 'Regional Office')], default='branch', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.country')),
            ],
        ),
        migrations.AddField(
            model_name='engineer',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.officelocation'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('client', models.CharField(blank=True, max_length=200)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('technologies_used', models.CharField(blank=True, help_text='Comma-separated list', max_length=500)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='articles.engineer')),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.engineer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='engineer',
            name='specializations',
            field=models.ManyToManyField(related_name='engineers', to='articles.specialization'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='articles.engineer')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['latitude', 'longitude'], name='articles_of_latitud_7c2990_idx'),
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['city', 'country'], name='articles_of_city_c379e0_idx'),
        ),
        migrations.AddIndex(
            model_name='engineer',
            index=models.Index(fields=['city', 'country'], name='articles_en_city_874abf_idx'),
        ),
        migrations.AddIndex(
            model_name='engineer',
            index=models.Index(fields=['latitude', 'longitude'], name='articles_en_latitud_0f399d_idx'),
        ),
        migrations.AddIndex(
            model_name='engineer',
            index=models.Index(fields=['is_verified', 'is_active'], name='articles_en_is_veri_9f81b7_idx'),
        ),
    ]
