# Generated by Django 5.2.6 on 2025-10-06 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_country_specialization_engineer_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='featured_level',
            field=models.PositiveIntegerField(default=1, help_text='Featured level from 1 (lowest) to 5 (highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
