# Generated by Django 5.2.6 on 2025-10-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_engineer_featured_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='featured_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Optional external or campaign feature ID', null=True),
        ),
    ]
