# Generated by Django 5.2.6 on 2025-09-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocial',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
