# Generated by Django 5.2.6 on 2025-09-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_usersocial_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocial',
            old_name='platform',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usersocial',
            unique_together={('user', 'name')},
        ),
    ]
