# Generated by Django 5.2.6 on 2025-10-02 10:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_contactmessage_alter_articlecomment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('architectural_design', 'Architectural Design'), ('urban_planning', 'Urban Planning'), ('housing', 'Housing'), ('restoration', 'Restoration'), ('ideas', 'Ideas Competition')], max_length=50)),
                ('target_audience', models.CharField(choices=[('professionals', 'Professionals'), ('students', 'Students'), ('open', 'Open for All')], default='open', max_length=50)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('submission_end', models.DateTimeField()),
                ('results_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('prizes', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('jury', models.JSONField(blank=True, default=list)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='competitions/covers/')),
                ('participant_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Competitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('participant_type', models.CharField(choices=[('professional', 'Professional'), ('student', 'Student'), ('enthusiast', 'Enthusiast')], max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_members', models.JSONField(blank=True, default=list, null=True)),
                ('project_title', models.CharField(blank=True, max_length=500, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('submitted', 'Project Submitted'), ('shortlisted', 'Shortlisted'), ('winner', 'Winner'), ('disqualified', 'Disqualified')], default='registered', max_length=50)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='articles.competition')),
            ],
            options={
                'verbose_name_plural': 'Participants',
                'unique_together': {('competition', 'email')},
            },
        ),
    ]
