# Generated by Django 5.2.6 on 2025-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_competition_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='bio',
            field=models.TextField(default='Default bio text', max_length=250),
        ),
    ]
