# Generated by Django 5.2.6 on 2025-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_engineer_featured_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photographer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Source'),
        ),
    ]
